import { Lead, ContentPost, LiveActivity, Workflow, Session, CommunityMember, CoachEvent } from './types';

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'L-01',
    name: 'Sarah Jones',
    email: 'sarah.j@example.com',
    source: 'LinkedIn',
    sourceIcon: 'link',
    status: 'New',
    responseTime: '12m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuMxYK8SfCskcxgww2LIFKb6RpIRJV44wgqZxfSCI2pgOMLV6N7vEtay-9MEtRilPJ_-Y1Evd4jWM9HWK7Wvo5kIdP-etDacfpeppju0tPDGSMksfTiurQv1mNdl2UUlMbTN2isnO9BUqNBmAM1AxuIaxitZthAgKsBxqgyd1jtYpLX4ox3gB-bEuzX7bXQgjOBUrrXz2934ATB1Z9x5GXTh1vXdIlBvYvNKI7EnV0nXGP6isyvpbRGKpuU4eXwd4pzjaMiXL-yZg',
  },
  {
    id: 'L-02',
    name: 'Tomas Eriksson',
    email: 't.eriksson@consultancy.se',
    source: 'Web Form',
    sourceIcon: 'article',
    status: 'Responded',
    responseTime: '2h 45m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBiO7gMaP6lOHfuhgkzY1SVzS7pPL7RZy-ERtGyER9EPBjj0fODQht5NjV69r1Nv1ApdOBJtZKlrT2wipuCXDjDb2LQGWNZ5aOeURpbJcEhSaFc5YqCXSL6bFD3S98tQUrJqndW40fm095hTAnljGF0gtpo-X7OqE2K7Iwx_3ldtRdwfqOIOw-VN7o8tRUXxRwKkd7F7pNmRmYmrL056WYrxTiOwn2jTK5EkXr1WQdr-4ggtWkZWEJ8zmV7MYk5dFZxdPp2CMkNLRw',
  },
  {
    id: 'L-03',
    name: 'Marta Kowalski',
    email: 'marta.k@techgrowth.pl',
    source: 'Referral',
    sourceIcon: 'share',
    status: 'Booked',
    responseTime: '5m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDnn63ji1A7Tmm4_uvx5gpQ_t6xQDG33e-ba_isFjMAQ_ogzYcwOWGPnVBJXcAKeX7FFXGP7Fea3aHdKtmQgyudQAO-x12u109HWlzwP85G1QfoUz1zXuYQArFL-V4LEAT--tUFu-vonfJ9PS2wH6mOCT64xxUOXuibrbRmmSVR1c_L7Q4y2IAu9hJVxNt0puxhY3b0myC3VaX3rjY2-55F27IG3bJgIrw-j-IoZRoFDf01us0g-ZMVbWMgEN7cIOJG17Fr_5Yrj_o',
  },
  {
    id: 'L-04',
    name: 'Anika Sharma',
    email: 'anika.sharma@global.com',
    source: 'LinkedIn',
    sourceIcon: 'link',
    status: 'New',
    responseTime: '1h 12m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDLVa8fegVJ1vt_akAx3aaZne8rcqgiY47-t-wgltUyvjevN5h8CLBuwd5mDXVOHvHg4SmiV2O_xUlIPRx4VN6lBMHzJb3XiwY9xiZUPcOqFQ1Mv0DNlB4GpJQ3ELDuBx63CzvCwCxXvM4qWHb4nYVtAXhVbTiTvdl7Txa23tGZ9BGCTdVy4i5Mk3uxF8Fjj6anlidShxjA1ouM-aemzJWYz_c7Bz685sqU7n2vwezNUT-inUgLQ3f6kxt3XC2S6AnmsgKX97za_EQ',
  },
  {
    id: 'L-05',
    name: 'Javier Moreno',
    email: 'j.moreno@creative.es',
    source: 'Direct Email',
    sourceIcon: 'mail',
    status: 'In Session',
    responseTime: '--',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCsNGKxiSpsag9cqPzPHfD7hX8XabhGScsPeFs_DdPdSDKVh7y6u5d-vyYRWfJcLTxbWr2Klx6CNHo4gdGaO3Xs4FwMrC2eetqBHNeHCIxb4X5SYgPlmgGFglWxCW8rM4BvyakAOEDe4SuTR37Gn49Td9XSo0QBkEBI7OmkZR72OS-POzoQUhcdMDon_xwyJHShz0j_1Tkw1IFPWD70L80kK4vrfRjOZ4uXk3_M1jn-CICsrBNNybnr20tt1xIfDTSW_7HsM0FFRIA',
  },
  {
    id: 'L-06',
    name: 'Priya Nair',
    email: 'p.nair@ventures.in',
    source: 'Web Form',
    sourceIcon: 'article',
    status: 'New',
    responseTime: '42m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMS1V6EzIu5lO3YOjUUqNQNNu6VuBumdmo0U9L8Upu6QmC4jeLoLM0bNOpzSsu6qleIKAMX8Dg-TQZsOZnBQ452WmwG3PWs2OpTkYQf0hPc1uZxXXmz1UIh8M-hiFEJVFXyZWiUX9PpBN4W0ONDh1vezVB2yIl_t278VCmh1_h0-18pyfwSwidBuYHT-U_FCTo-4yOnFWrsGYDo5MZl8_51OQQf7DTK5rbmLhzxHhRzJOTTkl_aAmOYDWcy83Hi7Vyh8P6wRVwrXc',
  },
  {
    id: 'L-07',
    name: 'Lena Bergström',
    email: 'lena.b@nordicfit.com',
    source: 'Referral',
    sourceIcon: 'share',
    status: 'Booked',
    responseTime: '18m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbH4qADtAZ9R0gPDoq3y3SeNwaEbQuvVX6RebpuDEsq_Wxwysm_bR2Do8C2TtNOaMvPsmgz3Bu03WN2GPH3uQKhx2m8I2d2paZqp6EjViLHXVwBzFbRsye5yP7ikbxihlUa7v_jU9HrRPK8ZflGEymWyZa8v1DrjNakou-lZPboav5wyQcnlsd0JDzXvAtZ09_nigAnyQzYK8vCbHt5G41q_Kr-HrIMLDqIs6nGBF1MlNeiTVKPv-6plqdUnv4Fk0zQx8rzR5iE8I',
  },
  {
    id: 'L-08',
    name: 'Daniel Müller',
    email: 'd.mueller@logistics.de',
    source: 'LinkedIn',
    sourceIcon: 'link',
    status: 'Responded',
    responseTime: '3h 20m',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1ay5S8Q4mwitvgyp5NU7P4wVXuYC59yrWHOQNDv6txo2nFEJyihfKQr8fe60eRxyxYz22p2XvrT6GmYVEO-dUkN4p3_gVrhcqFU2TMfX-iZnQ4xu2mFXp-5orCl9ltUYY21G7lVA-yFV7f_xFQxVMRQk8cANShsSLhKO0JELUP8YVsDUTGmd6BDtD1JmTlUDWltroPR-rraed1q3WgNg6LtmQyUPL1_M40fYc91Ef3K7mQvZ4y0PBnjwmwJ0ztnXkt_0xwoN4_p4',
  },
];

export const INITIAL_POSTS: ContentPost[] = [
  {
    id: 'P-01',
    preview: '"3 frameworks for high-performing teams I\'ve used this year..."',
    date: 'May 12, 2024',
    reactions: 142,
    comments: 28,
    reposts: 12,
    dms: 17,
    topTrigger: 'DM CTA',
    mediaType: 'image',
  },
  {
    id: 'P-02',
    preview: '"Why most coaching programs fail within 6 months..."',
    date: 'May 08, 2024',
    reactions: 98,
    comments: 15,
    reposts: 4,
    dms: 2,
    topTrigger: 'Educational',
    mediaType: 'description',
  },
  {
    id: 'P-03',
    preview: '"Comment \'READY\' to get my sales scripts for free!"',
    date: 'May 05, 2024',
    reactions: 215,
    comments: 84,
    reposts: 21,
    dms: 12,
    topTrigger: 'Keyword',
    mediaType: 'tag',
  },
];

export const INITIAL_LIVE_ACTIVITIES: LiveActivity[] = [
  {
    id: 'A-01',
    event: 'Comment Lead Capture',
    leadClient: 'Sarah Jenkins',
    status: 'Processed',
    time: '2m ago',
    icon: 'chat_bubble',
    iconBg: 'bg-primary-container/10',
    iconColor: 'text-primary'
  },
  {
    id: 'A-02',
    event: 'Inquiry Auto-Response',
    leadClient: 'Marcus Thorne',
    status: 'Sent',
    time: '14m ago',
    icon: 'auto_awesome',
    iconBg: 'bg-tertiary/10',
    iconColor: 'text-tertiary'
  },
  {
    id: 'A-03',
    event: 'Comment Lead Capture',
    leadClient: 'Elena Rodriguez',
    status: 'Processed',
    time: '28m ago',
    icon: 'chat_bubble',
    iconBg: 'bg-primary-container/10',
    iconColor: 'text-primary'
  },
  {
    id: 'A-04',
    event: 'Payment Failed Hook',
    leadClient: 'John Davis',
    status: 'Retry Scheduled',
    time: '1h ago',
    icon: 'error',
    iconBg: 'bg-error-container/20',
    iconColor: 'text-error'
  },
  {
    id: 'A-05',
    event: 'Comment Lead Capture',
    leadClient: 'Liam O\'Neill',
    status: 'Processed',
    time: '2h ago',
    icon: 'chat_bubble',
    iconBg: 'bg-primary-container/10',
    iconColor: 'text-primary'
  },
  {
    id: 'A-06',
    event: 'Inquiry Auto-Response',
    leadClient: 'Chloe Chen',
    status: 'Sent',
    time: '3h ago',
    icon: 'auto_awesome',
    iconBg: 'bg-tertiary/10',
    iconColor: 'text-tertiary'
  },
];

export const INITIAL_WORKFLOWS: Workflow[] = [
  {
    id: 'W-01',
    name: 'Post-Inquiry',
    description: 'Sends welcome kit and scheduling link after form submission',
    lastTriggered: '2 mins ago',
    badge: 'High Priority',
    enabled: true,
  },
  {
    id: 'W-02',
    name: 'Comment Lead Capture',
    description: 'Extracts leads from IG and Facebook post comments',
    lastTriggered: '14 mins ago',
    badge: 'Social',
    enabled: true,
  },
  {
    id: 'W-03',
    name: 'Community Onboarding',
    description: 'Adds new students to Discord and Circle platforms',
    lastTriggered: '1 hour ago',
    badge: 'Engagement',
    enabled: true,
  },
  {
    id: 'W-04',
    name: 'Webinar Reminder',
    description: 'Drip sequence for registered webinar attendees',
    lastTriggered: '3 hours ago',
    badge: 'Events',
    enabled: true,
  },
  {
    id: 'W-05',
    name: 'Session Report Generator',
    description: 'Processes audio to PDF reports using OpenAI/Zapier',
    lastTriggered: 'In Progress',
    badge: 'Processing',
    enabled: true,
    pulse: true,
  },
  {
    id: 'W-06',
    name: 'Payment Success Flow',
    description: 'Stripe to Notion database sync for tracking',
    lastTriggered: '4 hours ago',
    badge: 'FinOps',
    enabled: true,
  },
  {
    id: 'W-07',
    name: 'Dormant Client Re-engagement',
    description: 'Email triggers after 30 days of inactivity',
    lastTriggered: 'Yesterday',
    badge: 'Retention',
    enabled: true,
  },
  {
    id: 'W-08',
    name: 'Daily Metrics Aggregator',
    description: 'Compiles daily KPI summary from Google Sheets',
    lastTriggered: '8 hours ago',
    badge: 'Internal',
    enabled: true,
  },
  {
    id: 'W-09',
    name: 'Certificate Auto-Issuer',
    description: 'Failed to connect to Canva API. Check credentials.',
    lastTriggered: 'Failed 10m ago',
    badge: 'Critical Error',
    enabled: true,
  },
  {
    id: 'W-10',
    name: 'Legacy Mailchimp Sync',
    description: 'Syncing legacy list (Deprecated)',
    lastTriggered: '15 days ago',
    badge: 'Maintenance',
    enabled: false,
  },
];

export const INITIAL_SESSIONS: Session[] = [
  {
    id: 'S-01',
    clientName: 'Marta Kowalski',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxwwmIOgy54MqWZBjUsLNVLkEQD_KrRgJEFkfFbD6pRWRgIYP9MtlNHTnhuS7A61jS3fFR5RsGghBHXN55LD65PufTHhw5HpgAK5y9xDk2QjIy07KoUWgz0Bi52RIKVSBhn5FfwYY8MTZ2T9Zwaah0AQ88sE9sYrx2Xv-pJI5Bi6fcB959iz-GpiTz11N3fbFwhl_2ZIXcwt4sHmGD1wjGP5QdZG28_2Jaec_TWuEOEkB86eSLOYNJZhrcUB59WCSwWkOVLzwOmR4',
    sessionInfo: 'Session 4 of 12',
    dateTime: 'May 28 • 10:00 AM',
    duration: 60,
    aiReport: 'Ready',
    notes: 'The client detailed high-growth plans for TechGrowth and agreed to finalize the team alignment strategy by June 15th. Key action items placed for onboarding three senior directors.',
  },
  {
    id: 'S-02',
    clientName: 'Tomas Eriksson',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA67OO3JbqN_XFWzjEsYvkqr7OcYVfeWNAG-8BqIz1d113nGvmgMJpqQ2TIO0cTSkWcoBafvE5SBRjTVKRyoJKG0bw8nX8aBybCLHit8l1zxNpRXV9TGoLo9nBzM0dFNaa6uGAPXD9XosL35yOmTdKb26tt8KFIXoC222UoyoZ_Yl-zK5kLtECS2Quj8rX8-aIolJl1Q4z5ZxVZckXgQHR_nvSGyv5JppT7vE3WquKZa-JXHS0RWYI6L0kXSwvuZljppK0_7Dp1RTQ',
    sessionInfo: 'Session 7 of 12',
    dateTime: 'May 27 • 2:30 PM',
    duration: 50,
    aiReport: 'Ready',
    notes: 'Focused on consultancy business expansion into Nordic regions. Actionable milestones include scheduling follow-up webinars for local agencies.',
  },
  {
    id: 'S-03',
    clientName: 'Anika Sharma',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3Hat7rCly2_iqiJKfjGlSh3L93jdG6lwTfoPQuSMjFsNZnxNJxx8YvwLqcN5PBHGrcGM6vIIknJf8dt1WvL7t518mmnLMQChOwWeg6tdQde-4eSEhDiUnC2_q82i0MZEBWkkBR008FNn-lzKqkCv6-xQ8XyOxJuySoMexD8NyR_kysAc8-ri5jnQE6U4hNKnmgXoSRZbF6K8UmybMLqYOuTRUxJ1N04aUNSKSE6K9haPAXS0aq6TVbdS_Ftsgoew9V38rzpdd-Vg',
    sessionInfo: 'Session 2 of 12',
    dateTime: 'May 26 • 11:15 AM',
    duration: 60,
    aiReport: 'Processing',
  },
  {
    id: 'S-04',
    clientName: 'Javier Moreno',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0-TtKGXNdz7I_9k69wBvD9_VN0oxa69zxyxJBxp1U6UZK7Qpn8DpGri3zoSaHdOYgnqAGZrIKewFN0Jm-g3FKaRPhkcTqLcY3xeOEZsu6tdWlFjWQZ-0TLZo_r8kKS376kV5dNlz57G0hZV08NBsf8v3FeSt4N9aIEq-r9wD4fz84zg6bYpJovdSojKgt08WS3bIPsXl_Qjff4JSMay-awZJ3PvZHbaRlBVUHFyf5sv0uWHUKn-KOSfCAf-w18JiUdnjZ-00_jM8',
    sessionInfo: 'Session 11 of 12',
    dateTime: 'May 25 • 4:00 PM',
    duration: 45,
    aiReport: 'Ready',
    notes: 'Reviewed creative designs and brand playbook. Discussed launching direct newsletters to subscribers.',
  },
  {
    id: 'S-05',
    clientName: 'Priya Nair',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDsHzhUaJ7dSH22PDGfJ2zyw5LzxWPh97hfRp-LhhRQcPe2_8aIvH7eZXbcDwD_9-JmL_60HKnpzdU3udo076KWJBJDHn4cAiRr-dHqPr2noWCgC9_9s370oh13JwWv7EUDDOeqle72AuUyqQmcV64150hGTExvVvzxrATHpDcxCL3L4lUFoshh-WMe13eSMVnVU5cbnHo5RML6YbAARmUb5CGLH1iaifGrfCEJS3NKuc6wsN162Xo2mm_ZVzQNWg5dwrh4KjwJ6UI',
    sessionInfo: 'Session 1 of 12',
    dateTime: 'May 24 • 9:00 AM',
    duration: 60,
    aiReport: 'No Transcript',
  },
  {
    id: 'S-06',
    clientName: 'Daniel Müller',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuATu1ALx3X3gVHCTR43OtJ8FQ6P2ceP_bRv0LUOoOy-bQkRLZibtCOI-cXXoGfgDMAA1jeSlmj9eOefEF456spKOBDDXDMTnNqUN0nz5BbEjqEiK3O931uyjRUjPHE29QF1Xj260FKFImKysag8MPwqtAo5Odx3-Bo-fh8TH8rPms_rzwrPx6313VPiPoNzKkIo7gRMxWD-lCbGGqdG3POAOVR5WaR_Oq483hPmrdFmlXwds7tQMmzOps9rVyO-MvUqZR2U660HpSI',
    sessionInfo: 'Session 9 of 12',
    dateTime: 'May 22 • 1:00 PM',
    duration: 55,
    aiReport: 'Ready',
    notes: 'Strategized on logistics workflow optimization. Set clear targets for freight delivery metrics.',
  },
];

export const INITIAL_MEMBERS: CommunityMember[] = [
  {
    id: 'M-01',
    name: 'Anika Sharma',
    joinDate: 'May 12, 2024',
    onboardingStatus: 'Completed',
    lastActive: 'Today, 09:12 AM',
    eventsAttended: 14,
    initials: 'AS',
    avatarColorClass: 'bg-primary-container/20 text-primary',
  },
  {
    id: 'M-02',
    name: 'Lena Bergström',
    joinDate: 'May 24, 2024',
    onboardingStatus: 'Day 5 Drip',
    lastActive: 'Yesterday',
    eventsAttended: 2,
    initials: 'LB',
    avatarColorClass: 'bg-tertiary-container/20 text-tertiary',
  },
  {
    id: 'M-03',
    name: 'Javier Moreno',
    joinDate: 'May 26, 2024',
    onboardingStatus: 'Day 3 Drip',
    lastActive: '2 hours ago',
    eventsAttended: 0,
    initials: 'JM',
    avatarColorClass: 'bg-secondary-container text-secondary',
  },
  {
    id: 'M-04',
    name: 'Sarah Jones',
    joinDate: 'Apr 30, 2024',
    onboardingStatus: 'Completed',
    lastActive: '3 days ago',
    eventsAttended: 28,
    initials: 'SJ',
    avatarColorClass: 'bg-primary-container/20 text-primary',
  },
  {
    id: 'M-05',
    name: 'Daniel Müller',
    joinDate: 'May 27, 2024',
    onboardingStatus: 'Day 2 Drip',
    lastActive: 'Online',
    eventsAttended: 1,
    initials: 'DM',
    avatarColorClass: 'bg-error-container text-error',
  },
  {
    id: 'M-06',
    name: 'Priya Nair',
    joinDate: 'May 05, 2024',
    onboardingStatus: 'Completed',
    lastActive: '1 week ago',
    eventsAttended: 8,
    initials: 'PN',
    avatarColorClass: 'bg-on-tertiary-fixed-variant text-tertiary-fixed',
  },
];

export const INITIAL_EVENTS: CoachEvent[] = [
  {
    id: 'E-01',
    title: 'ICF Webinar: Ethical Coaching Boundaries',
    month: 'May',
    day: '31',
    timeRange: '14:00 - 15:30 GMT',
    locationType: 'Zoom',
    location: 'Zoom (Member Link)',
    sent: true,
  },
  {
    id: 'E-02',
    title: 'Guest Speaker: Andrijana M. on Client Retention',
    month: 'Jun',
    day: '04',
    timeRange: '10:00 - 11:00 GMT',
    locationType: 'Studio',
    location: 'Studio B / Hybrid',
    sent: false,
  },
];

export const INITIAL_INTEGRATIONS = [
  {
    id: 'int-1',
    name: 'LinkedIn',
    description: 'Automate content publishing and prospect lead generation directly to your LinkedIn feed.',
    status: 'Connected',
    detail: 'Last synced 4m ago',
    icon: 'share',
    iconColor: 'text-primary',
  },
  {
    id: 'int-2',
    name: 'Fireflies.ai',
    description: 'Transcribe and analyze your coaching sessions automatically using AI-driven voice insights.',
    status: 'Connected',
    detail: 'Active listener',
    icon: 'record_voice_over',
    iconColor: 'text-tertiary',
  },
  {
    id: 'int-3',
    name: 'Cal.com',
    description: 'Open-source scheduling that syncs your availability across all coaching portals and calendars.',
    status: 'Connected',
    detail: '2 Calendars synced',
    icon: 'calendar_month',
    iconColor: 'text-on-surface',
  },
  {
    id: 'int-4',
    name: 'Supabase',
    description: 'Secure cloud database for custom client data storage and real-time backend synchronization.',
    status: 'Connected',
    detail: 'Connection healthy',
    icon: 'database',
    iconColor: 'text-[#3ECF8E]',
  },
  {
    id: 'int-5',
    name: 'Gemini',
    description: 'Leverage Google\'s advanced AI models for drafting session notes and client feedback summaries.',
    status: 'Connected',
    detail: 'Ultra 1.5 enabled',
    icon: 'auto_awesome',
    iconColor: 'text-primary-container',
  },
  {
    id: 'int-6',
    name: 'n8n',
    description: 'Orchestrate complex node-based workflows to automate every aspect of your coaching business.',
    status: 'Connected',
    detail: '12 Active workflows',
    icon: 'hub',
    iconColor: 'text-error',
  },
];
